# Generated by Django 5.2.4 on 2025-07-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_remove_order_items_order_status_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
