# Generated by Django 5.2.4 on 2025-07-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_order_ordered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
    ]
