# Generated by Django 5.2.4 on 2025-07-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_order_can_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_order_deletion', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'App Settings',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='can_delete',
        ),
    ]
